[workspace]
members = [
    "crates/origami",
]
name = "dojo"
version = "0.3.3"
description = "Community-maintained libraries for Cairo"
homepage = "https://github.com/dojoengine/dojo"

[workspace.dependencies]
dojo = { path = "crates/dojo-core" }

[scripts]
all = "scarb build && scarb test"